title: yūmi.ai
description: The Amazing stuff we are doing at yūmi.
copyright: Copyright © 2011-2023 yūmi labs ltd. All Rights Reserved.

author:
  name: yūmi team,
  email: hello@yumi.ai,
  url: https://yumi.ai/team/
sociallinks:
  - title: Email
    faSet: 'fas'
    faIcon: 'fa-envelope'
    url: 'mailto:hello@yumi.ai'
  - title: Twitter
    faSet: 'fab'
    faIcon: 'fa-twitter'
    url: 'https://twitter.com/yumiprotocol'
  - title: Github
    faSet: 'fab'
    faIcon: 'fa-github'
    url: 'https://github.com/yumiai'