title: yūmi.ai
description: Using decentralised smart-markets to solve hard problems, together.
copyright: Copyright © 2011-2023 yūmi labs ltd. All Rights Reserved.

author:
  name: yūmi team,
  email: hello@yumi.ai,
  url: https://yumi.ai/team/
sociallinks:
  - title: 'hello@yumi.ai'
    faSet: 'fas'
    faIcon: 'fa-envelope'
    url: 'mailto:hello@yumi.ai'
  - title: '@yumiprotocol'
    faSet: 'fab'
    faIcon: 'fa-twitter'
    url: 'https://twitter.com/yumiprotocol'
  - title: yumiai
    faSet: 'fab'
    faIcon: 'fa-github'
    url: 'https://github.com/yumiai'