name: Hugo Deploy to GH Pages
# Action to build a Hugo based site.
on: 
  workflow_dispatch:
  #push:
  #  branches:
  #    - main # default branch for pages source

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          enable_jekyll: false
          publish_dir: ./public
          publish_branch: hugo # Deploy branch, change to main to make public.
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: '82072426+wolstaeb@users.noreply.github.com'
          commit_message: ${{ github.event.head_commit.message }}